import { Client } from '@entities/client';

export const initClientState: Client = {
  id: 0,
  name: '',
  entrepreneur: '',
  all_limit: 0,
  balance: 0,
  critical_balance: 0,
  day_limit: 0,
  day_spent: 0,
  month_plan: 0,
  month_spent: 0,
  week_spent: 0,
  zero_days: 0,
  budget_adjustment: 0,
  is_budget_agreed: false,
  has_telegram: false,
  token: '',
  recommended_budget: null,
  current_invoice_id: null,
  low_balance_at: null,
  paid_at: null,
  zero_balance_at: null,
  companies: [],
};
